server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com # eureka服务端的实例名称
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false # false表示不向注册中心注册自己
#    fecth-registry: false # false表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务